# -*- coding: utf-8 -*-
"""Project_TIme_series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSgXxOATP969K_W3tnAl4XeUK2BQplN0

# **Project Name**: Reliance Industries Stock Forecast

# **Business Objective**

Predict the Reliance Industries Stock Price for the next 30 days.
There are Open, High, Low, and Close prices that you need to obtain from the web for the day starting from 2015 to 2022, for the Reliance Industries stock.

# **Import Libraries**
"""

import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,mean_absolute_percentage_error
try:
    from pmdarima import auto_arima
    PMDARIMA_AVAILABLE=True
except:
    PMDARIMA_AVAILABLE=False

from google.colab import files
files.upload()

"""#**Import File**"""

df=pd.read_excel("/content/Company stock prices.xlsx")
df.head()

"""#**Shape**"""

df.shape

df.size

df.columns

"""# **Info**"""

df.info()

"""# **Duplicates**"""

df.duplicated().sum()

"""# **Missing Values**"""

df.isnull().sum()

"""# **Statistical values**"""

df.describe(include="all")

"""# **Data Preprocessing**"""

df = df.reset_index()
df["Date"]=pd.to_datetime(df["Date"],errors="coerce")
df=df.sort_values("Date")
df=df.drop_duplicates(subset="Date")
required_columns=["Open","High","Low","Close"]
for col in required_columns:
    df[col]=pd.to_numeric(df[col],errors="coerce")
df=df.dropna(subset=["Date","Close"])
df=df.set_index("Date")
df=df.sort_index()

df

"""# **Reliance Industries Closing Price Trend**"""

plt.figure(figsize=(10,6))
plt.plot(df.index,df["Close"],label="Closing Price")
plt.title("Reliance Industries Closing Price")
plt.xlabel("Date")
plt.ylabel("Close Price")
plt.xticks(rotation=45)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

df["MA20"]=df["Close"].rolling(20).mean()
df["MA50"]=df["Close"].rolling(50).mean()

"""# **Reliance Industries Short-Term Trend**"""

plt.figure(figsize=(15,6))
plt.plot(df.index,df["Close"],label="Close")
plt.plot(df.index,df["MA20"],label="20-Day Moving Average")
plt.plot(df.index,df["MA50"],label="50-Day Moving Average")
plt.title("Reliance Industries Short-Term Trend")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.grid(True)
plt.show()

df["MA200"]=df["Close"].rolling(200).mean()

"""# **Reliance Industries Long-Term Trend**"""

plt.figure(figsize=(15,6))
plt.plot(df.index,df["Close"],label="Close")
plt.plot(df.index,df["MA200"],label="200-Day Moving Average")
plt.title("Reliance Industries Long-Term Trend")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.grid(True)
plt.show()

"""# **Reliance Industries Daily Returns**"""

df["Daily_Return"]=df["Close"].pct_change()
plt.figure(figsize=(15,5))
plt.plot(df.index,df["Daily_Return"])
plt.title("Reliance Industries Daily Returns")
plt.xlabel("Date")
plt.ylabel("Daily Return")
plt.grid(True)
plt.show()

"""# **20-Day Rolling Volatility**"""

df["Rolling_Volatility"]=df["Daily_Return"].rolling(20).std()
plt.figure(figsize=(15,5))
plt.plot(df.index,df["Rolling_Volatility"])
plt.title("20-Day Rolling Volatility")
plt.xlabel("Date")
plt.ylabel("Volatility")
plt.grid(True)
plt.show()

"""#  **ADF STATIONARITY TEST**"""

def adf_test(series,name):
    result=adfuller(series.dropna())
    print("\n"+"="*60)
    print(name)
    print("="*60)
    print("ADF Statistic:",result[0])
    print("p-value:",result[1])
    print("Critical Values:")
    for key,value in result[4].items():
        print(key,":",value)
    if result[1]<0.05:
        print("Conclusion: Stationary")
    else:
        print("Conclusion: Non-Stationary")
adf_test(df["Close"],"Original Closing Price")

"""# **Differencing**"""

df["Close_Diff"]=df["Close"].diff()
adf_test(df["Close_Diff"],"First Differenced Closing Price")

"""# **ACF**"""

plot_acf(df["Close_Diff"].dropna(),lags=40)
plt.title("ACF - Differenced Closing Price")
plt.show()

"""# **PACF**"""

plot_pacf(df["Close_Diff"].dropna(),lags=40,method="ywm")
plt.title("PACF - Differenced Closing Price")
plt.show()

"""# **Time-Series Preparation**"""

ts=df["Close"].copy()
ts=ts.asfreq("B")
ts=ts.ffill()
print("\nTime Series Observations:",len(ts))

"""# **Feature Engineering**

# **Time-Based Train-Test Split**
"""

TEST_SIZE=252
if len(ts)<=TEST_SIZE:
    raise ValueError("Dataset does not contain enough observations for a one-year test set.")
train=ts.iloc[:-TEST_SIZE]
test=ts.iloc[-TEST_SIZE:]
print("\nTraining Period:",train.index.min(),"to",train.index.max())
print("Testing Period:",test.index.min(),"to",test.index.max())
print("Training Size:",len(train))
print("Testing Size:",len(test))

"""# **Evaluation Function**"""

def evaluate_model(model_name,actual,predicted):
    mae = mean_absolute_error(actual,predicted)
    mse = mean_squared_error(actual,predicted)
    rmse = np.sqrt(mse)
    r2 = r2_score(actual, predicted)
    mape = (np.mean(np.abs((actual - predicted)/ actual ))* 100)
    mape_accuracy = (100 - mape)
    return {"Model": model_name,"MAE": mae,
            "MSE": mse,"RMSE": rmse,"R2": r2,"MAPE": mape,
            "MAPE_Accuracy": mape_accuracy}
results=[]
predictions={}

"""# **Machine Learning Models**

# **MODEL 1 - NAIVE FORECAST**
"""

naive_pred=pd.Series(train.iloc[-1],index=test.index)
results.append(evaluate_model("Naive Forecast",test,naive_pred))
predictions["Naive Forecast"]=naive_pred
print("\nModel 1 - Naive Forecast")
print(results[-1])

"""# **MODEL 2 - HOLT-WINTERS**"""

hw_model=ExponentialSmoothing(train,trend="add",damped_trend=True,seasonal=None)
hw_fit=hw_model.fit(optimized=True)
hw_pred=hw_fit.forecast(len(test))
hw_pred=pd.Series(hw_pred,index=test.index)
results.append(evaluate_model("Holt-Winters",test,hw_pred))
predictions["Holt-Winters"]=hw_pred
print("\nModel 2 - Holt-Winters")
print(results[-1])

"""# **MODEL 3 - ARIMA**"""

arima_model=ARIMA(train,order=(5,1,0))
arima_fit=arima_model.fit()
arima_pred=arima_fit.forecast(len(test))
arima_pred=pd.Series(arima_pred,index=test.index)
results.append(evaluate_model("ARIMA",test,arima_pred))
predictions["ARIMA"]=arima_pred
print("\nModel 3 - ARIMA")
print(results[-1])

"""# **MODEL 4 - SARIMA**"""

sarima_model=SARIMAX(train,order=(1,1,1),seasonal_order=(1,1,1,5),enforce_stationarity=False,enforce_invertibility=False)
sarima_fit=sarima_model.fit(disp=False)
sarima_pred=sarima_fit.forecast(len(test))
sarima_pred=pd.Series(sarima_pred,index=test.index)
results.append(evaluate_model("SARIMA",test,sarima_pred))
predictions["SARIMA"]=sarima_pred
print("\nModel 4 - SARIMA")
print(results[-1])

"""# **MODEL 5 - AUTO-ARIMA**"""

if PMDARIMA_AVAILABLE:
    auto_model=auto_arima(train,start_p=0,start_q=0,max_p=5,max_q=5,d=None,seasonal=False,stepwise=True,trace=True,error_action="ignore",suppress_warnings=True)
    auto_pred=auto_model.predict(n_periods=len(test))
    auto_pred=pd.Series(auto_pred,index=test.index)
    auto_order=auto_model.order
else:
    print("\npmdarima is not installed. Using a grid-search ARIMA fallback for Model 5.")
    best_aic=np.inf
    best_order=None
    best_fit=None
    for p in range(0,4):
        for d in range(0,2):
            for q in range(0,4):
                try:
                    candidate=ARIMA(train,order=(p,d,q)).fit()
                    if candidate.aic<best_aic:
                        best_aic=candidate.aic
                        best_order=(p,d,q)
                        best_fit=candidate
                except:
                    continue
    if best_fit is None:
        raise ValueError("Unable to fit the Auto-ARIMA fallback.")
    auto_pred=best_fit.forecast(len(test))
    auto_pred=pd.Series(auto_pred,index=test.index)
    auto_order=best_order
results.append(evaluate_model("Auto-ARIMA",test,auto_pred))
predictions["Auto-ARIMA"]=auto_pred
print("\nModel 5 - Auto-ARIMA")
print(results[-1])
print("Selected Order:",auto_order)

"""# **Model Comparison**"""

results_df=pd.DataFrame(results)
results_df=results_df.sort_values("RMSE").reset_index(drop=True)
results_df["Rank"]=results_df.index+1
results_df=results_df[["Rank","Model","MAE","RMSE","MAPE","R2","MSE"]]
print("\nMODEL COMPARISON")
display(results_df)

results_df.to_csv("model_results.csv",index=False)
print("Model results saved successfully.")

"""# **RMSE COMPARISON**"""

plt.figure(figsize=(12,6))
plt.bar(results_df["Model"],results_df["RMSE"])
plt.title("RMSE Comparison of Five Time-Series Models")
plt.xlabel("Model")
plt.ylabel("RMSE")
plt.xticks(rotation=30)
plt.grid(axis="y")
plt.tight_layout()
plt.show()

"""# **MAPE COMPARISO**N

"""

plt.figure(figsize=(12,6))
plt.bar(results_df["Model"],results_df["MAPE"])
plt.title("MAPE Comparison of Five Time-Series Models")
plt.xlabel("Model")
plt.ylabel("MAPE (%)")
plt.xticks(rotation=30)
plt.grid(axis="y")
plt.tight_layout()
plt.show()

"""# **ACTUAL VS ALL MODELS**"""

plt.figure(figsize=(16,8))
plt.plot(test.index,test.values,label="Actual",linewidth=2)
for model_name,pred in predictions.items():
    plt.plot(test.index,pred,label=model_name)
plt.title("Actual vs Forecasted Reliance Industries Stock Price")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.legend(bbox_to_anchor=(1.02,1),loc="upper left")
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Best Model Selection**"""

best_model_name=results_df.iloc[0]["Model"]
best_mae=results_df.iloc[0]["MAE"]
best_rmse=results_df.iloc[0]["RMSE"]
best_mape=results_df.iloc[0]["MAPE"]
best_prediction=predictions[best_model_name]
print("\n"+"="*60)
print("BEST MODEL")
print("="*60)
print("Model:",best_model_name)
print("MAE:",round(best_mae,4))
print("RMSE:",round(best_rmse,4))
print("MAPE:",round(best_mape,4),"%")

"""# **BEST MODEL VS ACTUAL**"""

plt.figure(figsize=(15,7))
plt.plot(test.index,test.values,label="Actual",linewidth=2)
plt.plot(test.index,best_prediction,label=best_model_name,linewidth=2)
plt.title("Actual vs Best Model Forecast")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.legend()
plt.grid(True)
plt.show()

"""# **RESIDUAL ANALYSIS**"""

residuals=test-best_prediction
plt.figure(figsize=(15,6))
plt.plot(residuals)
plt.axhline(0,linestyle="--")
plt.title("Residual Analysis - "+best_model_name)
plt.xlabel("Date")
plt.ylabel("Residual")
plt.grid(True)
plt.show()

"""# **RESIDUAL DISTRIBUTION**"""

plt.figure(figsize=(10,6))
plt.hist(residuals.dropna(),bins=40)
plt.title("Residual Distribution - "+best_model_name)
plt.xlabel("Residual")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

"""# **RETRAIN BEST MODEL ON FULL DATA**"""

if best_model_name=="Naive Forecast":
    future_values=np.repeat(ts.iloc[-1],30)
elif best_model_name=="Holt-Winters":
    final_fit=ExponentialSmoothing(ts,trend="add",damped_trend=True,seasonal=None).fit(optimized=True)
    future_values=final_fit.forecast(30).values
elif best_model_name=="ARIMA":
    final_fit=ARIMA(ts,order=(5,1,0)).fit()
    future_values=final_fit.forecast(30).values
elif best_model_name=="SARIMA":
    final_fit=SARIMAX(ts,order=(1,1,1),seasonal_order=(1,1,1,5),enforce_stationarity=False,enforce_invertibility=False).fit(disp=False)
    future_values=final_fit.forecast(30).values
elif best_model_name=="Auto-ARIMA":
    if PMDARIMA_AVAILABLE:
        final_fit=auto_arima(ts,start_p=0,start_q=0,max_p=5,max_q=5,d=None,seasonal=False,stepwise=True,trace=False,error_action="ignore",suppress_warnings=True)
        future_values=final_fit.predict(n_periods=30)
    else:
        final_fit=ARIMA(ts,order=auto_order).fit()
        future_values=final_fit.forecast(30).values

"""# **30-DAY FORECAST**"""

future_dates=pd.bdate_range(start=ts.index[-1]+pd.offsets.BDay(1),periods=30)
forecast_df=pd.DataFrame({"Date":future_dates,"Predicted_Close":future_values})
print("\n30-DAY FORECAST")
display(forecast_df)

"""# **FORECAST GRAPH**"""

plt.figure(figsize=(16,8))
recent_history=ts.tail(180)
plt.plot(recent_history.index,recent_history.values,label="Historical Price")
plt.plot(forecast_df["Date"],forecast_df["Predicted_Close"],label="30-Day Forecast - "+best_model_name,linewidth=2)
plt.axvline(ts.index[-1],linestyle="--",label="Forecast Start")
plt.title("Reliance Industries 30 Trading-Day Stock Price Forecast")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# **FORECAST SUMMARY**"""

current_price=float(ts.iloc[-1])
forecast_final=float(forecast_df["Predicted_Close"].iloc[-1])
price_change=forecast_final-current_price
percentage_change=(price_change/current_price)*100
print("\n"+"="*60)
print("FINAL FORECAST SUMMARY")
print("="*60)
print("Latest Closing Price:",round(current_price,2))
print("30-Day Forecast Price:",round(forecast_final,2))
print("Forecast Change:",round(price_change,2))
print("Forecast Change (%):",round(percentage_change,2),"%")
print("Best Model:",best_model_name)

"""# **PROJECT SUMMARY**"""

print("\n"+"="*60)
print("PROJECT COMPLETED")
print("="*60)
print("Company: Reliance Industries")
print("Models Used: 5")
print("1. Naive Forecast")
print("2. Holt-Winters")
print("3. ARIMA")
print("4. SARIMA")
print("5. Auto-ARIMA")
print("Best Model:",best_model_name)
print("Test RMSE:",round(best_rmse,4))
print("Test MAE:",round(best_mae,4))
print("Test MAPE:",round(best_mape,4),"%")
print("Forecast Horizon: 30 Trading Days")

"""# **Save Model**"""

import pickle
import os
os.makedirs("saved_model",exist_ok=True)
best_model_name=results_df.iloc[0]["Model"]
if best_model_name=="Holt-Winters":
    final_model=ExponentialSmoothing(ts,trend="add",seasonal=None,initialization_method="estimated").fit()
elif best_model_name=="ARIMA":
    final_model=ARIMA(ts,order=(1,1,1)).fit()
elif best_model_name=="SARIMA":
    final_model=ARIMA(ts,order=(1,1,1),seasonal_order=(1,1,1,5)).fit()
elif best_model_name=="Auto-ARIMA":
    from pmdarima import auto_arima
    final_model=auto_arima(ts,seasonal=False,stepwise=True,suppress_warnings=True)
else:
    final_model=None
if final_model is not None:
    with open("saved_model/reliance_best_model.pkl","wb") as file:
        pickle.dump(final_model,file)
    print("Best model:",best_model_name)
    print("Model saved successfully")
os.makedirs("data",exist_ok=True)
df.reset_index().to_csv("data/reliance_stock_data.csv",index=False)
print("Data saved successfully")

import os
os.makedirs("data",exist_ok=True)
clean_df=df.reset_index()[["Date","Open","High","Low","Close"]]
clean_df.to_csv("data/reliance_stock_data.csv",index=False)
print("Clean CSV saved successfully")
print(clean_df.columns.tolist())
print(clean_df.head())

